-- Add up migration script here

CREATE SCHEMA IF NOT EXISTS media_management;

-- Groups media_management.items together (tv shows)
CREATE TABLE IF NOT EXISTS media_management.collections (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title varchar(1024),
    description varchar(2048),
    created_at timestamp without time zone DEFAULT now()
);

-- Any media item
CREATE TABLE IF NOT EXISTS media_management.items (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title varchar(1024),
    description varchar(2048),
    created_at timestamp without time zone DEFAULT now()
);

-- Join table for collections and items
CREATE TABLE IF NOT EXISTS media_management.items_collections (
    collection_id bigint NOT NULL REFERENCES media_management.collections (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    media_id bigint NOT NULL REFERENCES media_management.items (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    season_num smallint,
    episode_num smallint,
    PRIMARY KEY (collection_id, media_id)
);
