-- Add up migration script here
CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TABLE IF NOT EXISTS user_management.sun_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    email varchar(150) UNIQUE NOT NULL,
    password varchar(128) NOT NULL,
    created_at timestamp without time zone DEFAULT now ()
);

CREATE UNIQUE INDEX IF NOT EXISTS user_management_users_email ON user_management.sun_users (email);

CREATE TABLE IF NOT EXISTS user_management.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    name varchar(64) UNIQUE NOT NULL,
    created_at timestamp without time zone DEFAULT now ()
);

CREATE TABLE IF NOT EXISTS user_management.permission_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    name varchar(64) UNIQUE NOT NULL,
    created_at timestamp without time zone DEFAULT now ()
);

CREATE TABLE IF NOT EXISTS user_management.users_permission_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    user_id bigint REFERENCES user_management.sun_users (id) UNIQUE,
    permission_id bigint REFERENCES user_management.permissions (id),
    permission_level_id bigint REFERENCES user_management.permission_levels (id),
    created_at timestamp without time zone DEFAULT now ()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_permission_levels_user_id ON user_management.users_permission_levels (user_id);
